### ISSUE TITLE
Fork, Commit, Merge - Medium Issue (React)

### ISSUE THREAD

**Issue by nikohoffren** [nikohoffren/fork-commit-merge#1109]
# Fork, Commit, Merge - Medium Issue (React)

## Create a To-Do List Application with Persistence
*Note: You don't have ask permission to start solving the issue or get assigned, since these issues are supposed to be always open for new contributors. The actions-user bot will reset the file back to previous state for the next contributor after your commit is merged. So you can just simply start working with the issue right away!*

## How to get started:

Start by navigating inside of the directory used in this project with the command:
```bash
cd tasks/react/medium/todo-app
```

Then run `npm i` to install Vite, React and all the necessary dependencies for the project.

After installing the dependencies you can open the `src` directory and `App.jsx` file, and start implementing your solution!
There is no need to add any CSS for this project, it already has the default Vite project styles.

## Description:

Your task is to create a simple To-Do list application in React that allows users to add, update, and delete To-Do items. Additionally, the state should be persisted to localStorage so that the data is not lost upon a browser refresh.

## Requirements:

-   Use React Hooks (useState, useEffect, etc.)
-    Use localStorage for state persistence

Include the following features:
-   Add a new To-Do item
-   Update an existing To-Do item
-   Delete a To-Do item
-   List all To-Do items

## How to run:
After you are done with the card, make sure you are in the `tasks/react/medium/todo-app` in your terminal and run `npm run dev` to start the Vite server. Then, open "http://localhost:5173/" in your browser to check how the app looks.

If it looks to be working fine, you are ready to make a pull request!

---

To work with this issue, you need to have npm and NodeJS installed to your local machine.
Check out [README.md](https://github.com/nikohoffren/fork-commit-merge/blob/main/README.md) for more instructions of installing npm and NodeJS as well as how to make a pull request.

---

## Why use Vite?

This React project uses Vite for near-instant server start-ups and incredibly fast hot module replacements, providing a smooth and efficient development experience.
Also Vite requires minimal setup, allowing us to focus on writing React code without getting bogged down in complex configurations.
If you want to learn more about Vite, check out the documentation:
[Vite Official Documentation](https://vitejs.dev/)

---

Feel free to ask any questions here if you have some problems!

#### Also, kindly give this project a star to enhance its visibility for new developers!

**Comment by akshayw1** [comment]
Assign

**Comment by nikohoffren** [comment]
> Assign

Hi! As it says on the description:
*Note: You don't have ask permission to start solving the issue or get assigned, since these issues are supposed to be always open for new contributors. The actions-user bot will reset the file back to previous state for the next contributor after your commit is merged. So you can just simply start working with the issue right away!*
