### ISSUE TITLE
Bug - Grammar mistake - README.md

### ISSUE THREAD

**Issue by ayushrakesh** [nikohoffren/fork-commit-merge#1116]
I have found two grammar mistakes in README.md file inside "Installing an IDE" section. 

"**Instructions of how to install..**"  should be "**Instructions on how to install...**"

"**can be found in our website..**" should be "**can be found on our website...**"

I have attached the screenshot of it, you can see below.

![Screenshot (80)](https://github.com/nikohoffren/fork-commit-merge/assets/115995339/ef919b77-a4c0-4528-84d3-b7181355ff00)

**Comment by ayushrakesh** [comment]
Please assign this issue to me.

**Comment by nikohoffren** [comment]
> Please assign this issue to me.

Sounds good, go ahead!
